/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Unit_testing_cw;

import org.junit.Test;
import static org.junit.Assert.*;

public class cw1test {
    @Test 
	public void D2Htest1() {
        assertEquals("Hexadecimal representation is: F", Dec2Hex.Dec2HexConv(new String[] {"15"}));
    }
}
